# Generated by Django 4.1.2 on 2022-11-14 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0004_alter_animal_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='picture',
            field=models.ImageField(blank=True, upload_to='animal/'),
        ),
    ]
