# Generated by Django 4.1.2 on 2022-11-08 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sintomas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sintomas',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='neumonia'),
        ),
    ]
